// Now this is where things starting to get real ugly without dynamic code loading, but hey, this file can be easily autogenerated.
package mod

import (
	"github.com/opesun/hypecms/api/context"
	"github.com/opesun/hypecms/modules/content"
	"github.com/opesun/hypecms/modules/skeleton"
	"github.com/opesun/hypecms/modules/user"
)

func GetHook(modname string, method string) func(*context.Uni) {
	var r func(*context.Uni)
	switch modname {
	case "content":
		r = content.Hooks[method]
	case "tag":

	case "user":
		r = user.Hooks[method]
	case "skeleton":
		r = skeleton.Hooks[method]
	}
	return r
}
