// Mivel a Go-ban dinamikus kódbetöltés nincs, ezért ez a modul betölti az összes létező modult, hogy utána
// kvázi "pszeudo-dinamikusan" meg tudjuk hívni.
package mod

import (
	"github.com/opesun/hypecms/api/context"
	"github.com/opesun/hypecms/modules/content"
	"github.com/opesun/hypecms/modules/user"
)

// Now this is where things starting to get real ugly without dynamic code loading, but hey, this file can be easily autogenerated.
func GetHook(modname string, method string) func(*context.Uni) {
	var r func(*context.Uni)
	switch modname {
	case "content":
		r = content.Hooks[method]
	case "tag":

	case "shop":

	case "user":
		r = user.Hooks[method]
	}
	return r
}
